### ISSUE TITLE
Please add saltychat support :) 

### ISSUE THREAD

**Issue by soniXx123** [joe-rogan-0001/joehud#1]
Hi, nice hud. Please can you add saltychat support?

**Comment by icecubepiso** [comment]
what? who using this.. :D

**Comment by joe-rogan-0001** [comment]
I don't think this is possible since joehud is written in LUA and SaltyChat is written in C# and there doesn't seem to be much demand for SaltyChat. The export `exports['joehud']:Voicelevel(voiceMode)` is the export used for the voice level and this can be used with almost any voice chat script written in LUA if you want to try integrate it.

**Comment by StuxxyOfficial** [comment]
Sorry to comment on a closed issue but the OP can look up how to call Lua exports from C# or vice versa. its not complicated at all.
